{
 "title": "Logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "logs",
   "description": "Contains only info level logs",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"client\"} | detected_level=\"info\" |~ \"(?i)${search}\""
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "description": "Contains only warn level logs",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"client\"} | detected_level=\"warn\" |~ \"(?i)${search}\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "description": "Contains only error level logs",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"client\"} | detected_level=\"error\" |~ \"(?i)${search}\""
    }
   ]
  }
 ]
}